MYSQL_DATABASE_HOST = 'localhost'
MYSQL_DATABASE_USER = 'root'
MYSQL_DATABASE_PASSWORD = '' 
MYSQL_DATABASE_DB = 'thaothoi'
SECRET_KEY = 'lRE6Pmsf8lgbSoluYcKvUUyUf2VozQl'
HOST = "0.0.0.0"
DEBUG = True